### ISSUE TITLE
Can't access data from any country

### ISSUE THREAD

**Issue by Pranjal-dew** [shner-elmo/TradingView-Screener#43]
Hi I'm trying to fetch data for other market data but im unable to do it.

PFA

![Capture1](https://github.com/user-attachments/assets/a995c5d1-b2ee-46e9-950b-69357c152b34)
![Capture2](https://github.com/user-attachments/assets/a2284c02-9d14-40e9-b176-d691260e46c3)

**Comment by shner-elmo** [comment]
Of course bro, I'm glad you are enjoying it.

The issue is that by default it filters just `america` stocks, but you can change it:
https://shner-elmo.github.io/TradingView-Screener/2.5.0/tradingview_screener/query.html#Query.set_markets

And use the `set_markets()` method instead of `where(Column('market') == ...)`, its also more performant.

---

And finally, if you even want to filter a column that its either value `X` or `Y`, don't do:
```py
Query().where(Column('some_column') == 'x' or 'y')
```
But instead do:
```py
Query().where(Column('some_column').isin(['x', 'y']))
```
