### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by sadegh** [shner-elmo/TradingView-Screener#44]
First of all I want to thank you for this great library.

I saw you added [a section for getting real time](https://github.com/shner-elmo/TradingView-Screener?tab=readme-ov-file#real-time-data) data, but seems like it was not completed. Can you please tell how we can use our auth token to get updated data?

Thanks

**Comment by shner-elmo** [comment]
Hey @sadegh, absolutely!
I've updated the Real-time data section in the README, have a look at it and let me know if it's clear or if there is anything else to add.

**Comment by sujata-appiot** [comment]
@shner-elmo , the README section for Real-time data access mentions how to use tradingview authentication to enable the real-time access.
How do we get the updates on a screener result then? Do we get any "onupdate" or "onchange" kind of event from this library which we can catch & process the updates?

**Comment by shner-elmo** [comment]
@sujata-appiot hey man, to anwser your question there is no such event/update.
Even if you look on how the screener is implemented in the website it simply refreshes every 60 seconds (or every 10 if you have a premium account).

You can accomplish the same thing with a for loop + time.sleep()

**Comment by shner-elmo** [comment]
@sujata-appiot 
Also even if you could pull new data every second, you shouldn't for two reasons:
1. Overworking the server; might get banned
2. The data you receive won't actually change because it only gets updated like every 10 seconds or smth. (I guess this is what the update-mode field tells you: how often your data is getting updated. Which again, depends also by your account if you have premium and live data for a given exchange)

Hope this helps
