### ISSUE TITLE
Live data

### ISSUE THREAD

**Issue by dreich** [shner-elmo/TradingView-Screener#54]
Hello, dear!

Please, tell, can I run get_scanner_data() in infinite loop?
May be any bans for high rated requests?

By the way, if I pass cookies=cookies to get_scanner_data() and if I don't, I get "streaming" update_mode for exchanges, not streaming_delayed.

**Comment by Stail7** [comment]
I can be mistaken, but the tradingview website allows screener auto update not frequently then every 10 seconds. I run mine once in a minute to not get (possibly) banned

**Comment by dreich** [comment]
This is very rare 10s

**Comment by Stail7** [comment]
you probably need to use a web socket then, not api requests, but screener doesn’t have it

**Comment by dreich** [comment]
O, I thought it is web socket. I need another library?

**Comment by Stail7** [comment]
Here is what the author told me about historical and possibly live data from TV: [link](https://github.com/shner-elmo/TradingView-Screener/issues/35#issuecomment-2222392049)
You can try to investigate that. I ended up using another API for my historical data needs tho. But If you’ll find something with Tradingview - let me know

**Comment by shner-elmo** [comment]
Hey guys.

> Please, tell, can I run get_scanner_data() in infinite loop?

This is outside the scope of this project, but you probably want to use the `sched` library to schedule the function...
https://stackoverflow.com/a/474543/18042558

**Comment by shner-elmo** [comment]
As correctly @Stail7 said, you would want to use a another library that uses their socket API for streaming prices in real time.

The screener API is made for filtering symbols/tickers not for live (second) data.

If you want to get minute resolution or even every 10 seconds, then yes, you can use this.
But for second live data you would want to use a web-socket library, otherwise, you're going to overwhelm the server. And potentially get banned.

**Comment by shner-elmo** [comment]
If there are others that are interested, we can work on another library for that.
